GET /customers/ANTON HTTP/1.1
Host: localhost:3000
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImZpcnN0bmFtZSI6IlZpbm9kIiwibGFzdG5hbWUiOiJLdW1hciIsImlhdCI6MTU5NjAwMjU0OTU1Mn0.b2xS7Raiw2XXe4__HsKYF0hPMBFW2ZzyVhMIUu9opsw
